### DISCUSSION TITLE
NAVER CLOUD를 이용한 인프라 환경 구성

### DISCUSSION THREAD

**Discussion by Junroot** [Junroot/Nomat#55] [개발]
### 서버 구성에 참고한 문서

- 서버 생성: https://guide.ncloud-docs.com/docs/server-create-vpc
- VPC 사용 예시: https://guide.ncloud-docs.com/docs/vpc-procedure-vpc
- bastion 서버 사용 예시: https://guide.ncloud-docs.com/docs/server-ts-access-architecture-vpc
- kubernetes 설정: https://guide.ncloud-docs.com/docs/k8s-k8sprep

**Comment by Junroot** [comment]
### VPC 구성

- 이름: nomat
- IP 주소 범위: 	10.0.0.0/16

### 서브넷

- 1차 분류: public/priavte 여부
- 2차 분류: 배포 환경

|이름|IP 주소 범위|
|-|-|
|nomat-public-prod|10.0.0.0/24|
|nomat-private-prod|10.0.1.0/24|
|nomat-public-dev|10.0.2.0/24|
|nomat-private-dev|10.0.3.0/24|
|nomat-public-prod-lb|10.0.4.0/24|
|nomat-private-prod-lb|10.0.5.0/24|
|nomat-public-dev-lb|10.0.6.0/24|
|nomat-private-dev-lb|10.0.7.0/24|

**Comment by Junroot** [comment]
### 서버 별 사용 인스턴스 타입

#### dev 환경 DB

- s2-g3

<img width="1513" alt="image" src="https://github.com/Junroot/Nomat/assets/4648244/1744f32d-b3dc-46fe-a6fc-c3b3dc5aeb47">

**Comment by Junroot** [comment]
## mariaDB 설치

### 1. 설치

```sh
sudo apt update
sudo apt install mariadb-server
sudo mysql_secure_installation
sudo systemctl start mariadb.service
```

### 2. 사용자 추가

- 모든 IP에서 사용을 허용하기 위해서 host는 와일드카드 '%'로 지정

```sh
sudo mariadb
GRANT ALL ON *.* TO 'nomat'@'%' IDENTIFIED BY <password> WITH GRANT OPTION;
FLUSH PRIVILEGES;
```

### 3. 외부 접속 설정

- 현재는 아래와 같이 127.0.0.1:3306만 LISTEN 중인 것을 확인할 수 있다.

<img width="760" alt="image" src="https://github.com/Junroot/Nomat/assets/4648244/ba02f586-3a3e-4ab7-b68c-a105c16fafce">

```sh
cd /etc/mysql
vi mariadb.cnf # 아래 예시대로 설정 추가
sudo systemctl restart mariadb.service
```

```
[mysqld]
skip-networking=0
skip-bind-address
```

- LISTEN 상태 확인

<img width="761" alt="image" src="https://github.com/Junroot/Nomat/assets/4648244/ddcc225a-8204-47f5-a572-f33392ce94a7">

## Datagrip에서 접속하는 방법

- SSH tunnel 사용을 추가한다.

<img width="549" alt="image" src="https://github.com/Junroot/Nomat/assets/4648244/0fd134f8-ad80-4738-a82a-1f17cfcf7764">

## 참고 자료

- https://www.swhosting.com/en/comunidad/manual/how-to-install-mariadb-on-ubuntu-2204
- https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/

**Comment by Junroot** [comment]
## dev 환경 배포 인프라 구성

```mermaid
block-beta
columns 1
client(("client"))
space
LoadBalancer
space
space
block:cluster
  S1["Spring Container"]
  S2["Spring Container"]
end
dockerHub["Docker Hub"]
space
github(("github"))
client-- ":443" -->LoadBalancer
LoadBalancer--":80"-->S1
LoadBalancer--":80"-->S2
github-->dockerHub
dockerHub --> cluster
```

- LB는 아래 참고해서 구성
  - https://guide.ncloud-docs.com/docs/k8s-k8suse-loadbalancer
- develop 브랜치에 merge 되면 빌드 후, docker hub에 push
  - 클러스터에서 docker hub로 이미지 가져와서 배포
- HPA 계획
  - min: 2, max: 5

### 작업 계획

- [x] merge시 이미지 생성 및 docker hub 배포
  - [x] Dockerfile 작성
- [x] 디플로이먼트 구성
  - [x] image push 시 클러스터 업데이트(https://argo-cd.readthedocs.io/en/stable/getting_started/)
- [x] HPA 구성
- [x] LB 구성

### DB 구성

- DB 관련 데이터(url, username, password)는 환경 변수로 관리
- 클러스터 내에 secret 으로 저장 후, 파드에 환경변수로 설정
  - https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/

**Reply by Junroot** [reply]
## 로드 밸런서 구성

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nomat-lb
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nlb"
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nomat-back
  type: LoadBalancer
```

참고 자료: https://guide.ncloud-docs.com/docs/k8s-k8suse-loadbalancer
